# GitHub Sponsors funding options
# These funding links will appear in the "Sponsor" button on the repository

# Custom funding links
custom: ['https://buymeacoffee.com/murphy52']

# Other supported platforms (uncomment if you use them)
# github: [murphy52]
# patreon: username
# ko_fi: username